[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#1b81ee"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#533e71"

# Color used for almost all text.
textColor = "#d2d2d2f6"